name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04 ]
    env:
      CMAKE_C_COMPILER: gcc
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies on ubuntu
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: sudo apt-get install -y libharfbuzz-dev
      - name: build
        run: |
          mkdir -p build
          cmake -B build
          cmake --build build
      - name: run
        run: ./build/foreex
